# Generated by Django 4.1.3 on 2022-11-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stegno',
            name='filename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stegno',
            name='key',
            field=models.CharField(max_length=50),
        ),
    ]
