# Generated by Django 4.1.3 on 2022-11-28 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_folder_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('user_key', models.CharField(max_length=100)),
                ('generated_key', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=150)),
                ('nonce', models.CharField(max_length=150)),
                ('tag', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Stegno',
        ),
    ]
