# Generated by Django 4.1.3 on 2022-12-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_steg_delete_stegno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
